### ISSUE TITLE
osx compile issue (regression)

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1503]
Osx build is broken in the commit 063d677ebb45bac5495d261e7ee7935a40e9f84a

```c++
[ 91%] Building CXX object dbms/src/Storages/System/CMakeFiles/clickhouse_storages_system.dir/StorageSystemZooKeeper.cpp.o
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp: In static member function 'static bool DB::IsFiniteImpl::execute(T)':
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1257:12: error: expected '(' before 'constexpr'
         if constexpr (std::is_same<T, float>::value)
            ^~~~~~~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1261:9: error: 'else' without a previous 'if'
         else if constexpr (std::is_same<T, double>::value)
         ^~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1261:17: error: expected '(' before 'constexpr'
         else if constexpr (std::is_same<T, double>::value)
                 ^~~~~~~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1265:9: error: 'else' without a previous 'if'
         else
         ^~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp: In static member function 'static bool DB::IsInfiniteImpl::execute(T)':
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1276:12: error: expected '(' before 'constexpr'
         if constexpr (std::is_same<T, float>::value)
            ^~~~~~~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1280:9: error: 'else' without a previous 'if'
         else if constexpr (std::is_same<T, double>::value)
         ^~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1280:17: error: expected '(' before 'constexpr'
         else if constexpr (std::is_same<T, double>::value)
                 ^~~~~~~~~
/Users/silviu.caragea/Desktop/ClickHouse/dbms/src/Functions/FunctionsMiscellaneous.cpp:1284:9: error: 'else' without a previous 'if'
         else
         ^~~~
[ 91%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsRound.cpp.o
[ 91%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsStringSearch.cpp.o
[ 91%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsURL.cpp.o
At global scope:
cc1plus: error: unrecognized command line option '-Wno-unused-private-field' [-Werror]
cc1plus: all warnings being treated as errors
make[3]: *** [dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsMiscellaneous.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 91%] Linking CXX static library libclickhouse_storages_systemd.a
[ 91%] Built target clickhouse_storages_system
Scanning dependencies of target clickhouse_table_functions
```

**Comment by proller** [comment]
can you use newer clang ? (3.9+)

**Comment by silviucpp** [comment]
Build instructions changed ?

I'm using:

cmake .. -DCMAKE_CXX_COMPILER=`which g++-6` -DCMAKE_C_COMPILER=`which gcc-6` -DCMAKE_CXX_FLAGS="-I/usr/local/include" -DCMAKE_BUILD_TYPE=Release
make -j 16 clickhouse

Silviu

**Comment by silviucpp** [comment]
Hello,

using clang works fine

**Comment by alexey-milovidov** [comment]
BTW, gcc-7 is also Ok.

**Comment by silviucpp** [comment]
@alexey-milovidov I just updated to last master and last xcode but only clang works. 

```
cmake .. -DCMAKE_CXX_COMPILER=`which g++-7` -DCMAKE_C_COMPILER=`which gcc-7` -DCMAKE_CXX_FLAGS="-I/usr/local/include" -DCMAKE_BUILD_TYPE=Debug
```
```
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-7
-- Check for working C compiler: /usr/local/bin/gcc-7 -- broken
CMake Error at /usr/local/Cellar/cmake/3.9.6/share/cmake/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/usr/local/bin/gcc-7" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /Users/silviu.caragea/Desktop/ClickHouse/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_8761e/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_8761e.dir/build.make CMakeFiles/cmTC_8761e.dir/build

  Building C object CMakeFiles/cmTC_8761e.dir/testCCompiler.c.o

  /usr/local/bin/gcc-7 -o CMakeFiles/cmTC_8761e.dir/testCCompiler.c.o -c
  /Users/silviu.caragea/Desktop/ClickHouse/build/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTC_8761e

  /usr/local/Cellar/cmake/3.9.6/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_8761e.dir/link.txt --verbose=1

  /usr/local/bin/gcc-7 -Wl,-search_paths_first
  -Wl,-headerpad_max_install_names
  CMakeFiles/cmTC_8761e.dir/testCCompiler.c.o -o cmTC_8761e

  ld: library not found for -lSystem

  collect2: error: ld returned 1 exit status

  make[1]: *** [cmTC_8761e] Error 1

  make: *** [cmTC_8761e/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/silviu.caragea/Desktop/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/Users/silviu.caragea/Desktop/ClickHouse/build/CMakeFiles/CMakeError.log".
```
