### ISSUE TITLE
Compilation problem introduced in recent commit

### ISSUE THREAD

**Issue by kreuzerkrieg** [yandex/ClickHouse#5836]
in commit 90898905e0644352fedee8a87016c0ea17f12bc3

> ../dbms/src/Interpreters/ExternalLoader.cpp:406:32: error: unused variable ‘name’ [-Werror=unused-variable]
>          for (auto & [name, info] : infos)

it wouldnt compile with gcc-7.4, the default of Ubuntu Bionic...
The actual bug report https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=81767

**Comment by alexey-milovidov** [comment]
Ok, I will make a patch.

BTW, releases are build with gcc-8 and we are going to drop support for gcc-7.
And it does not matter what compiler is in OS packages as you can always install newer compiler.

**Comment by kreuzerkrieg** [comment]
and I definitely will once you leave me no choice :) meanwhile I prefer to work with default set of tools coming from official OS repo

**Comment by alexey-milovidov** [comment]
#5840
