### ISSUE TITLE
Can't build Clickhouse v1.1.54139-testing agains libpoco from Debian

### ISSUE THREAD

**Issue by jbfavre** [yandex/ClickHouse#414]
Hello,
I got error when building clickhouse v1.1.54139-testing against libpoco provided by Debian (and not the one embedded in clickhouse code tree):

```[ 98%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse-server.dir/InterserverIOHTTPHandler.cpp.o
In file included from /home/debocker/source/build/dbms/src/Server/InterserverIOHTTPHandler.cpp:3:0:
/home/debocker/source/build/dbms/include/DB/IO/WriteBufferFromHTTPServerResponse.h: In member function 'void DB::WriteBufferFromHTTPServerResponse::startSendHeaders()':
/home/debocker/source/build/dbms/include/DB/IO/WriteBufferFromHTTPServerResponse.h:81:66: error: 'class Poco::Net::HTTPServerResponse' has no member named 'beginSend'; did you mean 'begin'?
    std::tie(response_header_ostr, response_body_ostr) = response.beginSend();
                                                                  ^~~~~~~~~
In file included from /home/debocker/source/build/dbms/src/Server/HTTPHandler.cpp:14:0:
/home/debocker/source/build/dbms/include/DB/IO/WriteBufferFromHTTPServerResponse.h: In member function 'void DB::WriteBufferFromHTTPServerResponse::startSendHeaders()':
/home/debocker/source/build/dbms/include/DB/IO/WriteBufferFromHTTPServerResponse.h:81:66: error: 'class Poco::Net::HTTPServerResponse' has no member named 'beginSend'; did you mean 'begin'?
    std::tie(response_header_ostr, response_body_ostr) = response.beginSend();
```

Building v1.1.54135-stable works.
Faulty code seems to have been introduced in commit c9b761f7b6c0d47789c4ba95a7f6ade755c7b4c7

Poco version in Debian sid is `1.7.6`, libversion is `41`
Poco embedded in clickhouse is `1.6.1`, libversion is `36`

Regards,
JB

**Comment by proller** [comment]
Yes, compatibility with upstream poco again broken. i will fix it in few days.

**Comment by jbfavre** [comment]
Build now works with 1.1.54152-1
2 tests are failing (`00302_http_compression` & `00416_progress_in_http_headers`) but I think this is because I use `USE_STATIC_LIBRARIES=0` build flag.
Will check that asap

**Comment by jbfavre** [comment]
Both commits also works for v1.1.54144-stable, with same tests failing..
But removing `USE_STATIC_LIBRARIES=0` build flag leads to another error.
Investigating

**Comment by alexey-milovidov** [comment]
In fact, the patch is not ready.
Proller will take care of it in few days.

**Comment by jbfavre** [comment]
Ok, no problem. Thanks for the info :)

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/083e9cc3aa0886b599d5d6994b8d49bd066d8c39
https://github.com/yandex/ClickHouse/commit/131283de5bc8c80988a31d65b17829d6af062b42

**Comment by jbfavre** [comment]
Sucessfully tested with `v1.1.54159-stable`.
Works well, except for test `00416_progress_in_http_headers`
I had to patch it to remove some curl calls because of `send_progress_in_http_headers` not being implemented in `v1.1.54159-stable`:
```
$ curl -sS 'http://localhost:8123/?max_block_size=1&send_progress_in_http_headers=1&http_headers_progress_interval_ms=0&enable_http_compression=1' -H 'Accept-Encoding: gzip' -d 'SELECT number FROM system.numbers LIMIT 10' | gzip -d
Code: 115, e.displayText() = DB::Exception: Unknown setting send_progress_in_http_headers, e.what() = DB::Exception
```

Also had to patched `00416_progress_in_http_headers.reference` to remove `X-ClickHouse-Progress` headers not being sent for same reason

**Comment by jbfavre** [comment]
Also tested with `v1.1.54162-testing`.
Test `00416_progress_in_http_headers` fails because Clickhouse doen't send `X-ClickHouse` headers

```
curl -vsS 'http://localhost:8123/?max_block_size=1&send_progress_in_http_headers=1&http_headers_progress_interval_ms=0' -d 'SELECT number FROM system.numbers LIMIT 10' 2>&1
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8123 (#0)
> POST /?max_block_size=1&send_progress_in_http_headers=1&http_headers_progress_interval_ms=0 HTTP/1.1
> Host: localhost:8123
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 42
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 42 out of 42 bytes
< HTTP/1.1 200 OK
< Date: Sun, 12 Feb 2017 18:08:04 GMT
< Connection: Keep-Alive
< Content-Type: text/tab-separated-values; charset=UTF-8
< Transfer-Encoding: chunked
< Keep-Alive: timeout=3
< 
0
1
2
3
4
5
6
7
8
9
```

**Comment by proller** [comment]
X-ClickHouse-Progress works only with internal patched poco.
if https://github.com/pocoproject/poco/pull/1574 will be accepted - we make this header working for next poco versions (2.0+ ?)

**Comment by jbfavre** [comment]
I'll patch the reference file then, so that the test pass.
Thanks for the information !

**Comment by proller** [comment]
also note new UNBUNDLED cmake option (makes USE_INTERNAL_* = 0 with fallback if not found)
and with USE_STATIC_LIBRARIES=0 now generated one big libclickhouse.so and small all executables
my current todo: make options USE_INTERNAL_*=0 for all libs in contrib/

**Comment by jbfavre** [comment]
Great, will have a look at it.
My own todo is how to make `00281_gcc_clang_sizeof_packed` pass without Clickhouse being installed.

Also, I think UNBUNDLED, USE_INTERNAL_* and USE_STATIC_LIBRARIES might have some impact in `./dbms/src/Interpreters/Compiler.cpp` because of libray headers not being at the same place, am I right ?
