### ISSUE TITLE
build failed on osx with clang 

### ISSUE THREAD

**Issue by flowbehappy** [yandex/ClickHouse#1488]
tag: v1.1.54310-testing, tag: v1.1.54310-stable

Build commands:

```
mkdir build
cd build
cmake ..
make -j 4 clickhouse
```

The building process is good without errors, but the linking process fail on last step:

```
[100%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse-server.dir/StatusFile.cpp.o
[100%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse-server.dir/TCPHandler.cpp.o
[100%] Linking CXX static library libclickhouse-server.a
[100%] Built target clickhouse-server
[100%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse-local.dir/LocalServer.cpp.o
[100%] Linking CXX static library libclickhouse-client.a
[100%] Built target clickhouse-client
[100%] Linking CXX static library libclickhouse-local.a
[100%] Built target clickhouse-local
[100%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse.dir/main.cpp.o
[100%] Linking CXX executable clickhouse
Undefined symbols for architecture x86_64:
  "_current_memory_tracker", referenced from:
      DB::AsynchronousBlockInputStream::readImpl() in libclickhouse-client.a(Client.cpp.o)
      DB::AsynchronousBlockInputStream::next() in libclickhouse-client.a(Client.cpp.o)
      DB::AsynchronousBlockInputStream::calculate(MemoryTracker*) in libclickhouse-client.a(Client.cpp.o)
      DB::ProcessListElement::~ProcessListElement() in libdbms.a(Context.cpp.o)
      DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::readImpl() in libdbms.a(StorageDistributed.cpp.o)
      DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long) in libdbms.a(StorageDistributed.cpp.o)
      DB::UnionBlockInputStream<(DB::StreamUnionMode)1>::readImpl() in libdbms.a(InterpreterCheckQuery.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [dbms/src/Server/clickhouse] Error 1
make[2]: *** [dbms/src/Server/CMakeFiles/clickhouse.dir/all] Error 2
make[1]: *** [dbms/src/Server/CMakeFiles/clickhouse.dir/rule] Error 2
make: *** [clickhouse] Error 2
```

The clang version:
```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Found CUDA installation: /usr/local/cuda, version 8.0
```

Note that it goods well if I compile with gcc 7. i.e. 
```
cmake .. -DCMAKE_CXX_COMPILER=`which g++-7` -DCMAKE_C_COMPILER=`which gcc-7`
```

**Comment by vavrusa** [comment]
I just attempted to build it with the same problem, I'll see if it's fixable with current clang.

**Comment by vavrusa** [comment]
It's broken since 443088ce3134b1c61e9bc746ed9306bdf0f4c067 (the `extern thread_local` isn't properly supported in the current apple clang). cc @proller

**Comment by flowbehappy** [comment]
👍

**Comment by alexey-milovidov** [comment]
It seems to be fixed.

BTW, it's easy to install the most fresh clang in Mac OS if you have any troubles:
```
git clone git@github.com:llvm-project/llvm-project-20170507.git
cd llvm-project-20170507
mkdir build && cd build

CC=clang CXX=clang++ cmake -D LLVM_TARGETS_TO_BUILD='X86' -D LLVM_ENABLE_PROJECTS='clang;lld;polly' -D CMAKE_BUILD_TYPE=Release ../llvm
make -j $THREADS
sudo make install
```

**Comment by flowbehappy** [comment]
@alexey-milovidov  
Hi alexey, I installed llvm 5.0 with your script today. But when I tried to compile ClickHouse with it errors come:

```
ClickHouse/dbms/src/Common/StringUtils.h:3:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
```

Looks like it cannot find the libc++ headers. Any help?

**Comment by filimonov** [comment]
Relates #235
