### ISSUE TITLE
Kerberos error on CentOS build

### ISSUE THREAD

**Issue by kmatt** [yandex/ClickHouse#1622]
On CentOS 7.4.1708, v1.1.54310-stable was building without error. On v1.1.54318-stable I'm getting build errors that appear to be related to Kerberos 5. 

Have tried both -DOPENSSL_NO_KRB5=1 and -DUSE_STATIC_LIBRARIES=1 with no change. openssl{-devel, -libs, -static} is version in yum 1:1.0.2k-8.el7

Is there cmake option to not use Kerberos?

---

CMakeError.log:

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command:"/opt/rh/devtoolset-6/root/usr/bin/gmake" "cmTC_08866/fast"
/opt/rh/devtoolset-6/root/usr/bin/gmake -f CMakeFiles/cmTC_08866.dir/build.make CMakeFiles/cmTC_08866.dir/build
gmake[1]: Entering directory '/home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_08866.dir/CheckSymbolExists.c.o
/opt/rh/devtoolset-6/root/usr/bin/cc    -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer -Wall  -no-pie    -o CMakeFiles/cmTC_08866.dir/CheckSymbolExists.c.o   -c /home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_08866
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_08866.dir/link.txt --verbose=1
/opt/rh/devtoolset-6/root/usr/bin/cc    -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer -Wall  -no-pie     CMakeFiles/cmTC_08866.dir/CheckSymbolExists.c.o  -o cmTC_08866 -rdynamic
CMakeFiles/cmTC_08866.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_08866.dir/build.make:97: recipe for target 'cmTC_08866' failed
gmake[1]: *** [cmTC_08866] Error 1
gmake[1]: Leaving directory '/home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_08866/fast' failed
gmake: *** [cmTC_08866/fast] Error 2

File /home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp

Run Build Command:"/opt/rh/devtoolset-6/root/usr/bin/gmake" "cmTC_53f2e/fast"
/opt/rh/devtoolset-6/root/usr/bin/gmake -f CMakeFiles/cmTC_53f2e.dir/build.make CMakeFiles/cmTC_53f2e.dir/build
gmake[1]: Entering directory '/home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_53f2e.dir/CheckFunctionExists.c.o
/opt/rh/devtoolset-6/root/usr/bin/cc    -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer -Wall  -no-pie -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_53f2e.dir/CheckFunctionExists.c.o   -c /usr/share/cmake3/Modules/CheckFunctionExists.c
Linking C executable cmTC_53f2e
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_53f2e.dir/link.txt --verbose=1
/opt/rh/devtoolset-6/root/usr/bin/cc    -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer -Wall  -no-pie -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_53f2e.dir/CheckFunctionExists.c.o  -o cmTC_53f2e -rdynamic -lpthreads
/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_53f2e.dir/build.make:97: recipe for target 'cmTC_53f2e' failed
gmake[1]: *** [cmTC_53f2e] Error 1
gmake[1]: Leaving directory '/home/kmatt/projects/ClickHouse/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_53f2e/fast' failed
gmake: *** [cmTC_53f2e/fast] Error 2
```

Make output:

```
[ 78%] Building CXX object dbms/src/Storages/System/CMakeFiles/clickhouse_storages_system.dir/StorageSystemColumns.cpp.o
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x206): undefined reference to `valid_cksumtype'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x229): undefined reference to `krb5_checksum_size'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x26d): undefined reference to `krb5_checksum_size'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x93c): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x958): undefined reference to `krb5_kt_resolve'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x972): undefined reference to `krb5_kt_close'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x986): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x995): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x9cb): undefined reference to `krb5_kt_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x9fc): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0xa2a): undefined reference to `krb5_kt_get_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0xa4a): undefined reference to `krb5_kt_free_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xac1): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xadc): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xaf0): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xaff): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb54): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb6b): undefined reference to `krb5_cc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb86): undefined reference to `krb5_cc_get_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xbaa): undefined reference to `krb5_get_credentials'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xc63): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xc96): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xce1): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xcf5): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd09): undefined reference to `krb5_auth_con_free'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd18): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd5b): undefined reference to `krb5_cc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd75): undefined reference to `krb5_cc_get_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xe05): undefined reference to `krb5_get_credentials'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xe6f): undefined reference to `krb5_mk_req_extended'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0xff5): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x103b): undefined reference to `krb5_rc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1056): undefined reference to `krb5_timeofday'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1064): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x10dd): undefined reference to `krb5_rc_initialize'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x10f7): undefined reference to `krb5_rc_get_lifespan'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1112): undefined reference to `krb5_rc_destroy'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x17a6): undefined reference to `krb5_auth_con_free'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x17ce): undefined reference to `krb5_auth_con_init'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1805): undefined reference to `krb5_kt_close'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1819): undefined reference to `krb5_free_ticket'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x182f): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1877): undefined reference to `krb5_auth_con_getrcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18ab): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18d6): undefined reference to `krb5_auth_con_setrcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18ff): undefined reference to `krb5_kt_resolve'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1a67): undefined reference to `krb5_principal_compare'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1a99): undefined reference to `krb5_kt_get_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1b40): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1b7d): undefined reference to `krb5_get_server_rcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1c70): undefined reference to `krb5_kt_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1c9f): undefined reference to `krb5_decrypt_tkt_part'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1cfc): undefined reference to `krb5_kt_free_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_krb5_free_data_contents':
(.text+0xbc3): undefined reference to `krb5_free_data_contents'
collect2: error: ld returned 1 exit status
dbms/src/DataStreams/tests/CMakeFiles/union_stream2.dir/build.make:146: recipe for target 'dbms/src/DataStreams/tests/union_stream2' failed
make[2]: *** [dbms/src/DataStreams/tests/union_stream2] Error 1
CMakeFiles/Makefile2:7828: recipe for target 'dbms/src/DataStreams/tests/CMakeFiles/union_stream2.dir/all' failed
make[1]: *** [dbms/src/DataStreams/tests/CMakeFiles/union_stream2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsCoding.cpp.o
[ 78%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsComparison.cpp.o
[ 78%] Building CXX object dbms/src/AggregateFunctions/CMakeFiles/clickhouse_aggregate_functions.dir/AggregateFunctionGroupArrayInsertAt.cpp.o
[ 78%] Linking CXX executable sorting_stream
[ 78%] Linking CXX executable integer_hash_tables_and_hashes
[ 78%] Built target integer_hash_tables_and_hashes
[ 78%] Building CXX object dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/FunctionsConditional.cpp.o
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x206): undefined reference to `valid_cksumtype'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x229): undefined reference to `krb5_checksum_size'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_skip_confound':
(.text+0x26d): undefined reference to `krb5_checksum_size'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x93c): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x958): undefined reference to `krb5_kt_resolve'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x972): undefined reference to `krb5_kt_close'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x986): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x995): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x9cb): undefined reference to `krb5_kt_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0x9fc): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0xa2a): undefined reference to `krb5_kt_get_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_keytab_is_available':
(.text+0xa4a): undefined reference to `krb5_kt_free_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xac1): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xadc): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xaf0): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xaff): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb54): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb6b): undefined reference to `krb5_cc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xb86): undefined reference to `krb5_cc_get_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_tgt_is_available':
(.text+0xbaa): undefined reference to `krb5_get_credentials'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xc63): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xc96): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xce1): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xcf5): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd09): undefined reference to `krb5_auth_con_free'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd18): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd5b): undefined reference to `krb5_cc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xd75): undefined reference to `krb5_cc_get_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xe05): undefined reference to `krb5_get_credentials'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_cget_tkt':
(.text+0xe6f): undefined reference to `krb5_mk_req_extended'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0xff5): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x103b): undefined reference to `krb5_rc_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1056): undefined reference to `krb5_timeofday'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1064): undefined reference to `krb5_free_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x10dd): undefined reference to `krb5_rc_initialize'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x10f7): undefined reference to `krb5_rc_get_lifespan'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_validate_times':
(.text+0x1112): undefined reference to `krb5_rc_destroy'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x17a6): undefined reference to `krb5_auth_con_free'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x17ce): undefined reference to `krb5_auth_con_init'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1805): undefined reference to `krb5_kt_close'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1819): undefined reference to `krb5_free_ticket'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x182f): undefined reference to `krb5_free_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1877): undefined reference to `krb5_auth_con_getrcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18ab): undefined reference to `krb5_sname_to_principal'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18d6): undefined reference to `krb5_auth_con_setrcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x18ff): undefined reference to `krb5_kt_resolve'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1a67): undefined reference to `krb5_principal_compare'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1a99): undefined reference to `krb5_kt_get_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1b40): undefined reference to `krb5_init_context'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1b7d): undefined reference to `krb5_get_server_rcache'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1c70): undefined reference to `krb5_kt_default'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1c9f): undefined reference to `krb5_decrypt_tkt_part'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_sget_tkt':
(.text+0x1cfc): undefined reference to `krb5_kt_free_entry'
/lib/../lib64/libssl.a(kssl.o): In function `kssl_krb5_free_data_contents':
(.text+0xbc3): undefined reference to `krb5_free_data_contents'
collect2: error: ld returned 1 exit status
dbms/src/DataStreams/tests/CMakeFiles/sorting_stream.dir/build.make:146: recipe for target 'dbms/src/DataStreams/tests/sorting_stream' failed
make[2]: *** [dbms/src/DataStreams/tests/sorting_stream] Error 1
CMakeFiles/Makefile2:7974: recipe for target 'dbms/src/DataStreams/tests/CMakeFiles/sorting_stream.dir/all' failed
make[1]: *** [dbms/src/DataStreams/tests/CMakeFiles/sorting_stream.dir/all] Error 2
```

**Comment by filimonov** [comment]
Check that https://github.com/Altinity/clickhouse-rpm probably they solved that by builfing openssl in newer version

**Comment by kmatt** [comment]
Removing openssl-static and installing OpenSSL v1.1.0g from source allows successful builds on CentOS 6.9 and 7.4
