### ISSUE TITLE
MAP_POPULATE is not defined in OS X

### ISSUE THREAD

**Issue by halayli** [yandex/ClickHouse#6959]
clickhouse fails to compile on os x:

In file included from 

.../build/contrib/build/src/clickhouse/dbms/src/Common/PODArray.h:15:
.../build/contrib/build/src/clickhouse/dbms/src/Common/Allocator.h:182:32: error: use of undeclared identifier 'MAP_POPULATE'
            | (mmap_populate ? MAP_POPULATE : 0);
                               ^

**Comment by nicelulu** [comment]
Related https://github.com/yandex/ClickHouse/issues/6459.

**Comment by akuzm** [comment]
broken in https://github.com/yandex/ClickHouse/pull/6667

**Comment by akuzm** [comment]
Does #6974 help?
