### ISSUE TITLE
Packages for non-LTS Ubuntu

### ISSUE THREAD

**Issue by kyptov** [yandex/ClickHouse#124]
```
The following packages have unmet dependencies:
 clickhouse-client : Depends: libc6 (< 2.24) but 2.24-0ubuntu1 is to be installed
 clickhouse-server-common : Depends: clickhouse-server-base (= 1.1.54022) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I understand that Yakkety is not released, but will be soon.

**Comment by alexey-milovidov** [comment]
Yes, we currently have no automatic builds on 16.10.

By the way, there are two possibilities for us:
- add 16.10 to auto-builds;
- to experiment further with `GLIBC_COMPATIBILITY` build option (it removed dependency of specific version of libc): maybe we should enable it by default.

And you could either:
- build on 16.10;
- build on any other Ubuntu version with `GLIBC_COMPATIBILITY` option enabled and install anywhere.

**Comment by thias** [comment]
Just a side note : If `GLIBC_COMPATIBILITY` is changed to be the default, I hope it can still be disabled, since it makes the build fail for me on RHEL7 with glibc 2.17 and gcc 6.2.1 (it builds fine without) : 
```
[mockbuild@r2d2 build]$ make
[  0%] Built target cityhash
[  1%] Built target lz4
[  2%] Built target double-conversion
[  2%] Built target zstd
[  2%] Built target farmhash
[  2%] Built target metrohash
[ 18%] Built target PocoFoundation
[ 24%] Built target PocoXML
[ 25%] Built target PocoJSON
[ 33%] Built target PocoNet
[ 35%] Built target PocoMongoDB
[ 37%] Built target PocoUtil
[ 38%] Built target PocoCrypto
[ 41%] Built target PocoNetSSL
[ 44%] Built target PocoData
[ 44%] Building C object contrib/libpoco/Data/SQLite/CMakeFiles/PocoDataSQLite.dir/src/sqlite3.c.o
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c:26418:42: error: 'mremap' undeclared here (not in a function)
   { "mremap",       (sqlite3_syscall_ptr)mremap,          0 },
                                          ^~~~~~
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c: In function 'unixRemapfile':
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c:30750:42: error: 'MREMAP_MAYMOVE' undeclared (first use in this function)
     pNew = osMremap(pOrig, nReuse, nNew, MREMAP_MAYMOVE);
                                          ^~~~~~~~~~~~~~
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c:30750:42: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c:30750:42: error: passing argument 4 of '(void * (*)(void *, size_t,  size_t,  int))aSyscall[23].pCurrent' makes integer from pointer without a cast [-Werror=int-conversion]
/builddir/build/BUILD/ClickHouse-1.1.54022-stable/contrib/libpoco/Data/SQLite/src/sqlite3.c:30750:42: note: expected 'int' but argument is of type 'struct unix_syscall *'
cc1: all warnings being treated as errors
make[2]: *** [contrib/libpoco/Data/SQLite/CMakeFiles/PocoDataSQLite.dir/src/sqlite3.c.o] Error 1
make[1]: *** [contrib/libpoco/Data/SQLite/CMakeFiles/PocoDataSQLite.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by alexey-milovidov** [comment]
Thanks, I will remove SQLite from build. It is not used, and it is just an optional part of Poco/Data library.
(Probably it could be used as source for external dictionaries, if we will have request for it.)

**Comment by khamin** [comment]
Hello,

any update on it?
Same problem on 17.04 :)

**Comment by proller** [comment]
We have no builds fot 17.04
But you can build manually as described here:
https://github.com/yandex/ClickHouse/blob/master/doc/build_debian.sh
Or make package by running this script (dont forget install all depends):
https://github.com/yandex/ClickHouse/blob/master/release

**Comment by alexey-milovidov** [comment]
Fixed long time ago.
Now we have single set of packages for all Ubuntu/Debian flavours.
